### ISSUE TITLE
Needs tzdata, at least on Windows

### ISSUE THREAD

**Issue by dopplershift** [conda-forge/django-feedstock#132]
Django 4.0 needs `tzdata` on Windows, as show [here](https://github.com/django/django/blob/40165eecc40f9e223702a41a0cb0958515bb1f82/setup.cfg#L40-L44). Since this currently noarch, that would mean unconditionally depending on tzdata--which might be fine.

**Comment by ocefpaf** [comment]
I wonder if that is for all Pythons or just +3.9 b/c of the decision on not depending on tzdata there. Anyway, it is fine to add it here IMO.

**Comment by ocefpaf** [comment]
Looks like there is also a `backports.zoneinfo` dependency  for py<39. I'm not sure if we can just add that or if keeping the <39 is better, I haven't check. Either way, let's just remove noarch until we figure that out so we can have a nice working  4.0.1. See #133
