### ISSUE TITLE
create django_3.2.x LTS branch, 3.2.11

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/django-feedstock#135]
[Django 3.2.11](https://docs.djangoproject.com/en/4.0/releases/3.2.11) is out, and has a few security fixes.

It would be lovely to have a branch to target new PRs for this LTS series which has a solid year left in it.

**Comment by ocefpaf** [comment]
Sure. I can create the branch but I cannot commit on maintaining it.

**Comment by ocefpaf** [comment]
And done: https://github.com/conda-forge/django-feedstock/tree/3.2.x

**Comment by bollwyvl** [comment]
> And done:

Thanks! 

> cannot commit on maintaining it.

I'll probably be monitoring releases, will try to stay on top of the PRs, but seems unlikely anything _too_ exciting will happen... guess that's the point!
