### ISSUE TITLE
When will noarch/osx-arm64 channels be updated?

### ISSUE THREAD

**Issue by rogermilroy** [conda-forge/django-feedstock#147]
### Comment:

The current version on linux, osx-64, win-64 are all on 4.1.1 which is the latest but the noarch distribution is still on 4.0.0.

Could we get a timeline for when we can expect noarch channels to be updated if it will not be in line with the general distributions?

Also just a note that adding to the osx-arm64 channel if updating the noarch channel is too problematic would also solve my problem if not others.

<img width="983" alt="Screenshot 2022-10-04 at 19 15 44" src="https://user-images.githubusercontent.com/25173052/193805156-0f101136-cb52-4e8a-b8a0-3235c90aeb99.png">

**Comment by ocefpaf** [comment]
The package is no longer noarch due to dependencies change. There won't be an update there. Your `conda install` should be puling 4.11 for our arch, if that is not happening please re-open the issue.
