### ISSUE TITLE
Why is GDAL a depdency?

### ISSUE THREAD

**Issue by sdc50** [conda-forge/django-feedstock#16]
I'm curious to know why GDAL is needed as a dependency for the conda-forge version of Django (it is not a dependency on the defaults channel). I need to include Django 1.9*  as a dependency for a package I'd like to release, but need the flexibility of using it with the latest version of GDAL.

**Comment by ocefpaf** [comment]
It should be an optional dependency but `conda` does not have that concept yet. The original recipe was designed by some people that made heavy use of the `contrib/gis` parts of `Django` and the actual dependency was only added to test the patches that makes that possible during the build.

Maybe a more sensible way to do this is to test the patches locally but not enforcing the `gdal` as a dependency. However, to actually do this, we would need access to a `Windows` and `OS X` which we do not :unamused: That is why I use the CIs.

I will consider this but remember that you can always `pip` install stuff inside a `conda` environment. You can even specify `pip` dependencies in `environment.yml` files. So maybe we should keep supporting the harder install case, `django`+`gdal`, and leave the easy cases for `pip`. What do you think?

**Comment by sdc50** [comment]
The motivation is that we'd like to release [Tethys Platform](http://www.tethysplatform.org/) as a package on conda-forge, which currently depends on Django 1.9, but will likely be used with various versions of `gdal`. So we need to have `django` in our dependency list, but not `gdal`. As I understand, in order to release a package all of the dependencies also have to be on conda-forge, so getting `django` from `pip` is not an option in this case, is that correct? 

Please forgive my ignorance, but since you mentioned that `gdal` is only needed to test the patches during the build, would it work to only include `gdal` as a build dependency?

**Comment by ocefpaf** [comment]
> so getting `django` from `pip` is not an option in this case, is that correct? 

Correct.

> Please forgive my ignorance, but since you mentioned that `gdal` is only needed to test the patches during the build, would it work to only include `gdal` as a build dependency?

Not really only to test the patches. The users will need it at run time. But you are correct. To only tests the patches we can add only only at build time and inform users that they need to install `gdal` manually later. Do you want to send a PR to fix that? Note that we will need a version rotation too to include `django 1.9`.

**Comment by sdc50** [comment]
Thanks for the clarification. I'll work on a PR.

**Comment by ocefpaf** [comment]
Done in #18 and in another branch for the `1.9.x` version.
