### ISSUE TITLE
pytz as a run requirement?

### ISSUE THREAD

**Issue by synapticarbors** [conda-forge/django-feedstock#26]
It looks like `pytz` is  a run time requirement:

https://github.com/django/django/blob/master/setup.py#L50

This came up as an error in the following feedstock build:

https://travis-ci.org/conda-forge/django-filter-feedstock/jobs/238596886

**Comment by jakirkham** [comment]
Appears to have been added in ( https://github.com/django/django/commit/414ad25b090a63eaaf297b1164c8f7d814a710a2 ), which was added in version `1.11`.
