### ISSUE TITLE
django 1.11.9 version

### ISSUE THREAD

**Issue by sannykr** [conda-forge/django-feedstock#39]
Can you please tell me the branch where I should make a pull request for django 1.11.9

**Comment by sannykr** [comment]
following up!

**Comment by kwilcox** [comment]
I just pushed a django_1.11.x branch... it's building. Thanks for the poke!

**Comment by ocefpaf** [comment]
@sannykr you can send the PR to https://github.com/conda-forge/django-feedstock/tree/django_1.11.x now.

**Comment by sannykr** [comment]
@kwilcox @ocefpaf : Thanks. I really appreciate that.
