### ISSUE TITLE
Django version 1.7.11

### ISSUE THREAD

**Issue by astamminger** [conda-forge/django-feedstock#56]
Hi @kwilcox @ocefpaf,

I have yet another mummy that i would like to rise from the (almost) dead.
Could you tell me where I should push my recipe to? (Maybe you want to create a new 1.7.x branch)

Best,
Andreas

**Comment by ocefpaf** [comment]
Send a PR targeting master and I will create the maintenance branch.

**Comment by astamminger** [comment]
Thanks :+1:
