### ISSUE TITLE
Continue packaging django 2.2.x?

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/django-feedstock#91]
The 2.2.x line is still being [updated with CVE fixes](https://docs.djangoproject.com/en/dev/releases/2.2.10/): any chance we can get that added as a long-term branch? It all still builds cleanly with the 2.2.8 recipe and sha bump. Happy to do the PR if the branch exists to target!

**Comment by kwilcox** [comment]
Yes and more yes, I'll set this up. Thanks for the reminder.

**Comment by bollwyvl** [comment]
Thanks!

**Comment by kwilcox** [comment]
[django_2.2.x branch](https://github.com/conda-forge/django-feedstock/tree/django_2.2.x) is created, @ocefpaf how did I do?

**Comment by ocefpaf** [comment]
> [django_2.2.x branch](https://github.com/conda-forge/django-feedstock/tree/django_2.2.x) [](/conda-forge/django-feedstock/tree/HEAD@{2020-05-04T14:07:43Z}) is created, @ocefpaf how did I do?

Perfect! The build passed in https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=154274&view=results and the new package is already available in https://anaconda.org/conda-forge/django/files?version=2.2.8

Updates can be sent to that branch now.
